name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Run tests and generate HTML reports
        run: |
          mkdir -p reports
          pytest --html=reports/project_report.html

      - name: Upload tests report outside VM
        uses:  actions/upload-artifact@v3
        with:
          name: upload report
          path: reports/project_report.html


